services:
  letterboxd_mysql:
    image: mysql:latest
    env_file:
      - ./seeder/.env
    ports:
      - 3307:3306
    volumes:
      - mysql_data_letterboxd:/var/lib/mysql
    networks:
      - letterboxd_db_network

  letterboxd-backend:
    build:
      context: ./letterboxd-backend
    volumes:
      - ./letterboxd-backend:/app
      - /app/node_modules
    ports:
      - 5000 # external port 5050 for dev
    env_file:
      - ./letterboxd-backend/.env
    depends_on:
      - letterboxd_mysql
    networks:
      - letterboxd_db_network
      - letterboxd_backend_network

  letterboxd-frontend:
    build:
      context: ./letterboxd-frontend
    volumes:
      - ./letterboxd-frontend:/app
      - /app/node_modules
    ports:
      - 3000:3000
    env_file:
      - ./letterboxd-frontend/.env
    depends_on:
      - letterboxd-backend
    networks:
      - letterboxd_backend_network
      - letterboxd_frontend_network

  nginx-proxy:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - letterboxd-frontend
    networks:
      - letterboxd_frontend_network
      - letterboxd_backend_network

networks:
  letterboxd_db_network:
    driver: bridge
  letterboxd_backend_network:
    driver: bridge
  letterboxd_frontend_network:
    driver: bridge

volumes:
  mysql_data_letterboxd: