services:
  letterboxd_mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: letterboxd_db
    ports:
      - 3306
    volumes:
      - mysql_data_letterboxd:/var/lib/mysql
    networks:
      - letterboxd_db_network

  letterboxd-backend:
    build:
      context: ./letterboxd-backend
    volumes:
      - ./letterboxd-backend:/app
      - /app/node_modules
    ports:
      - 5000
    environment:
      - PORT=5000
      - DB_URL: mysql://root:rootpassword@letterboxd_mysql:3306/letterboxd_db
      - DB_TYPE: mysql
      - DB_SCHEMA: letterboxd_db
      - JWT_SECRET: your_jwt_secret
    depends_on:
      - letterboxd_mysql
    networks:
      - letterboxd_db_network
      - letterboxd_backend_network

  letterboxd-frontend:
    build:
      context: ./letterboxd-frontend
    volumes:
      - ./letterboxd-frontend:/app
      - /app/node_modules
    ports:
      - 3000
    environment:
      - VITE_API_URL=/api
      - PORT=3000
    depends_on:
      - letterboxd-backend
    networks:
      - letterboxd_backend_network
      - letterboxd_frontend_network

  nginx-proxy:
    image: nginx:alpine
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - letterboxd-frontend
    networks:
      - letterboxd_frontend_network
      - letterboxd_backend_network

networks:
  letterboxd_db_network:
    driver: bridge
  letterboxd_backend_network:
    driver: bridge
  letterboxd_frontend_network:
    driver: bridge

volumes:
  mysql_data_letterboxd: