services:
  mysql:
    image: mysql:latest
    env_file:
      - ./seeder/.env
    ports:
      - 3307:3306
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - db_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--password=rootpassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 5050:5000 # external port 5050 for dev
    env_file:
      - ./backend/docker.env
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - db_network
      # - backend_network

  # frontend:
  #   build:
  #     context: ./frontend
  #   volumes:
  #     - ./frontend/src:/app/src:cached
  #     - ./frontend/public:/app/public:cached
  #     - /app/node_modules
  #   ports:
  #     - 3000:3000
  #   env_file:
  #     - ./frontend/docker.env
  #   depends_on:
  #     - backend
  #   networks:
  #     - backend_network
  #     - frontend_network
  #   command: npm run dev

  # nginx-proxy:
  #   image: nginx:alpine
  #   ports:
  #     - 80:80
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf
  #   depends_on:
  #     - frontend
  #   networks:
  #     - frontend_network
  #     - backend_network

networks:
  db_network:
    driver: bridge
  # backend_network:
  #   driver: bridge
  # frontend_network:
  #   driver: bridge

volumes:
  mysql_data: